### ISSUE TITLE
num_rows inconsistent between model and view.

### ISSUE THREAD

**Issue by slevination** [sl-as-kj/tbl#37]
Right now, if there is a header and 5 rows in a file, then model will think that there are 6 rows total while view will think that there are 5.  This creates all sorts of wicked issues with last row.
In addition, num_rows method in a view is incorrect and shouldn't be used as there is nothing that updates it should the model change. Should view know about how many rows there are? (I am thinking yes) If so, how do we guarantee that the view and model are in sync?  Should view contain a pointer to a model?

Alex, how should this be addressed?

**Comment by alexhsamuel** [comment]
I'm refactoring stuff a bit to address this. But the layout stuff has gotten pretty complicated; I think I need to redesign it to make it sane.

**Comment by alexhsamuel** [comment]
@slevination can you confirm this is fixed now? If not, please give more details of remaining problems.

**Comment by slevination** [comment]
testing

**Comment by slevination** [comment]
fixed an issue with deletion of bottom most row.

**Comment by slevination** [comment]
This is still an issue.  Basically, the view has no clue as to how many rows it has (it's not synced to the model) so if you delete a last row and then try to navigate with arrows, the app gets confused.

**Comment by alexhsamuel** [comment]
I've merged `Screen` into `View` and cleaned up a lot of stuff. Next, I'll look at `View` and its `Layout`, and figure out exactly what the API will be for updating the view when the model changes.
